# Generated by counter/cask.sh in yehogwon/vibes. Edit it there.
cask "counter" do
  version "0.1.0"
  sha256 "debfdf7d720d066e5820a2ce036edd3e9f3810ab87da9a0ea3b00c5890320262"

  url "https://github.com/yehogwon/vibes/releases/download/counter-v#{version}/Counter-#{version}.zip"
  name "Counter"
  desc "Timers for the menu bar"
  homepage "https://github.com/yehogwon/vibes"

  # Matches LSMinimumSystemVersion in counter/Resources/Info.plist.
  depends_on macos: :sonoma

  app "Counter.app"

  # Counter is signed ad hoc and can't be notarized, so Gatekeeper would block it after every
  # install and upgrade. This can't be postflight_steps, as brew style's Cask/InstallSteps wants:
  # those run sandboxed, and macOS won't let a sandboxed process clear the quarantine flag.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Counter.app"]
  end

  uninstall quit: "io.github.yehogwon.Counter"

  # The iCloud Drive › Counter folder is left alone: deleting it would delete the timers on every
  # Mac.
  zap trash: [
    "~/Library/Application Support/Counter",
    "~/Library/Preferences/io.github.yehogwon.Counter.plist",
  ]

  caveats <<~EOS
    Counter is signed ad hoc, not notarized, so this cask clears its quarantine flag and macOS
    opens it without a Gatekeeper check.
  EOS
end
