# Generated by jots/cask.sh in yehogwon/vibes. Edit it there.
cask "jots" do
  version "0.4.1"
  sha256 "cf6926edede5ff8b3e40901dbbeb7d762d2545c8080e758fe00d89ef74ed835c"

  url "https://github.com/yehogwon/vibes/releases/download/jots-v#{version}/Jots-#{version}.zip"
  name "Jots"
  desc "Markdown scratchpad for the menu bar"
  homepage "https://github.com/yehogwon/vibes"

  # Matches LSMinimumSystemVersion in jots/Resources/Info.plist.
  depends_on macos: :sonoma

  app "Jots.app"

  # Jots is signed ad hoc and can't be notarized, so Gatekeeper would block it after every install
  # and upgrade. This can't be postflight_steps, as brew style's Cask/InstallSteps wants: those run
  # sandboxed, and macOS won't let a sandboxed process clear the quarantine flag.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Jots.app"]
  end

  uninstall quit: "io.github.yehogwon.Jots"

  # The iCloud Drive › Jots folder is left alone: deleting it would delete the text on every Mac.
  zap trash: [
    "~/Library/Application Support/Jots",
    "~/Library/Containers/io.github.yehogwon.Jots",
    "~/Library/Preferences/io.github.yehogwon.Jots.plist",
  ]

  caveats <<~EOS
    Jots is signed ad hoc, not notarized, so this cask clears its quarantine flag and macOS
    opens it without a Gatekeeper check.
  EOS
end
