# Generated by jots/cask.sh in yehogwon/vibes. Edit it there.
cask "jots" do
  version "0.1.0"
  sha256 "5f6c66f41c22a42c170dd823e23b3016688385807857867faf2464df7a8130e9"

  url "https://github.com/yehogwon/vibes/releases/download/jots-v#{version}/Jots-#{version}.zip"
  name "Jots"
  desc "Markdown scratchpad for the menu bar"
  homepage "https://github.com/yehogwon/vibes"

  # Matches LSMinimumSystemVersion in jots/Resources/Info.plist.
  depends_on macos: :sonoma

  app "Jots.app"

  uninstall quit: "io.github.yehogwon.Jots"

  # The iCloud Drive › Jots folder is left alone: deleting it would delete the text on every Mac.
  zap trash: [
    "~/Library/Application Support/Jots",
    "~/Library/Containers/io.github.yehogwon.Jots",
    "~/Library/Preferences/io.github.yehogwon.Jots.plist",
  ]

  caveats <<~EOS
    Jots is signed ad hoc, not notarized, so macOS blocks it the first time it opens. Allow it
    under System Settings › Privacy & Security › Open Anyway.
  EOS
end
