# Generated by moments/cask.sh in yehogwon/vibes. Edit it there.
cask "moments" do
  version "0.2.0"
  sha256 "b770774131afb8d3a79f7ebbb1b0d924aa8c28160b586cd1172ddf4d7e59cb23"

  url "https://github.com/yehogwon/vibes/releases/download/moments-v#{version}/Moments-#{version}.zip"
  name "Moments"
  desc "D-day countdowns for the menu bar"
  homepage "https://github.com/yehogwon/vibes"

  # Matches LSMinimumSystemVersion in moments/Resources/Info.plist.
  depends_on macos: :sonoma

  app "Moments.app"

  # Moments is signed ad hoc and can't be notarized, so Gatekeeper would block it after every
  # install and upgrade. This can't be postflight_steps, as brew style's Cask/InstallSteps wants:
  # those run sandboxed, and macOS won't let a sandboxed process clear the quarantine flag.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Moments.app"]
  end

  uninstall quit: "io.github.yehogwon.Moments"

  # The iCloud Drive › Moment folder is left alone: the original Moment syncs through it too, and
  # deleting it would delete the moments on every Mac.
  zap trash: [
    "~/Library/Application Support/Moments",
    "~/Library/Preferences/io.github.yehogwon.Moments.plist",
  ]

  caveats <<~EOS
    Moments is signed ad hoc, not notarized, so this cask clears its quarantine flag and macOS
    opens it without a Gatekeeper check.
  EOS
end
